/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    news: News;
    insights: Insight;
    jobs: Job;
    'hero-slides': HeroSlide;
    'hero-feature-cards': HeroFeatureCard;
    'membership-categories': MembershipCategory;
    'member-testimonials': MemberTestimonial;
    'team-members': TeamMember;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    'hero-feature-cards': HeroFeatureCardsSelect<false> | HeroFeatureCardsSelect<true>;
    'membership-categories': MembershipCategoriesSelect<false> | MembershipCategoriesSelect<true>;
    'member-testimonials': MemberTestimonialsSelect<false> | MemberTestimonialsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'wwd-homepage': WwdHomepage;
    'industry-councils-homepage': IndustryCouncilsHomepage;
    'cross-sector-councils-homepage': CrossSectorCouncilsHomepage;
    'membership-homepage': MembershipHomepage;
    'insights-homepage': InsightsHomepage;
    'event-homepage': EventHomepage;
    'get-involved-homepage': GetInvolvedHomepage;
    'news-homepage': NewsHomepage;
    'country-offices-page': CountryOfficesPage;
    'fellowship-page': FellowshipPage;
    'membership-page': MembershipPage;
    'get-involved-page': GetInvolvedPage;
    'partnerships-page': PartnershipsPage;
    'donate-page': DonatePage;
    'volunteer-page': VolunteerPage;
    'news-listing-page': NewsListingPage;
    'contact-page': ContactPage;
    'about-page': AboutPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'wwd-homepage': WwdHomepageSelect<false> | WwdHomepageSelect<true>;
    'industry-councils-homepage': IndustryCouncilsHomepageSelect<false> | IndustryCouncilsHomepageSelect<true>;
    'cross-sector-councils-homepage': CrossSectorCouncilsHomepageSelect<false> | CrossSectorCouncilsHomepageSelect<true>;
    'membership-homepage': MembershipHomepageSelect<false> | MembershipHomepageSelect<true>;
    'insights-homepage': InsightsHomepageSelect<false> | InsightsHomepageSelect<true>;
    'event-homepage': EventHomepageSelect<false> | EventHomepageSelect<true>;
    'get-involved-homepage': GetInvolvedHomepageSelect<false> | GetInvolvedHomepageSelect<true>;
    'news-homepage': NewsHomepageSelect<false> | NewsHomepageSelect<true>;
    'country-offices-page': CountryOfficesPageSelect<false> | CountryOfficesPageSelect<true>;
    'fellowship-page': FellowshipPageSelect<false> | FellowshipPageSelect<true>;
    'membership-page': MembershipPageSelect<false> | MembershipPageSelect<true>;
    'get-involved-page': GetInvolvedPageSelect<false> | GetInvolvedPageSelect<true>;
    'partnerships-page': PartnershipsPageSelect<false> | PartnershipsPageSelect<true>;
    'donate-page': DonatePageSelect<false> | DonatePageSelect<true>;
    'volunteer-page': VolunteerPageSelect<false> | VolunteerPageSelect<true>;
    'news-listing-page': NewsListingPageSelect<false> | NewsListingPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * CMS administrators and editors for africantradechamber.org
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Shown in the admin bar. Leave blank to use first + last name.
   */
  displayName?: string | null;
  jobTitle?: string | null;
  phone?: string | null;
  role?: ('admin' | 'editor') | null;
  /**
   * Optional — visible on your account page only.
   */
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Site media library — select or upload images used across pages and posts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Accessibility description shown when the image cannot be displayed.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Generic CMS pages served at /{slug}. Main site sections (About, Contact, etc.) are edited under Globals.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: ('chamber' | 'member' | 'press' | 'media' | 'newsletter') | null;
  featuredImage?: (number | null) | Media;
  /**
   * Legacy import URL; used when no Media item is selected.
   */
  imageUrl?: string | null;
  newsSource?: string | null;
  newsAuthor?: string | null;
  newsDate?: string | null;
  originalUrl?: string | null;
  featured?: boolean | null;
  priority?: ('low' | 'medium' | 'high') | null;
  expiryDate?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category: 'trade-market-brief' | 'sector-report' | 'investment-snapshot' | 'policy-paper';
  author?: string | null;
  featuredImage?: (number | null) | Media;
  /**
   * Legacy import URL; used when no Media item is selected.
   */
  imageUrl?: string | null;
  originalUrl?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  slug: string;
  department?: string | null;
  location?: string | null;
  jobType?: string | null;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  requirements?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('open' | 'closed') | null;
  applyUrl?: string | null;
  jobId?: string | null;
  category?: string | null;
  postedAt?: string | null;
  roleHtml?: string | null;
  responsibilitiesHtml?: string | null;
  aboutHtml?: string | null;
  qualificationsHtml?: string | null;
  competenciesHtml?: string | null;
  locationScope?: string | null;
  appointment?: string | null;
  requirementsHtml?: string | null;
  processHtml?: string | null;
  deadline?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  title: string;
  description?: string | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  backgroundImage?: (number | null) | Media;
  /**
   * Legacy import URL; used when no Media item is selected.
   */
  backgroundImageUrl?: string | null;
  sideImage?: (number | null) | Media;
  /**
   * Legacy import URL; used when no Media item is selected.
   */
  sideImageUrl?: string | null;
  /**
   * MP4 URL for right-side video (slide 3)
   */
  sideVideoUrl?: string | null;
  showSideImage?: boolean | null;
  showApplyOnly?: boolean | null;
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-feature-cards".
 */
export interface HeroFeatureCard {
  id: number;
  title: string;
  description: string;
  linkText?: string | null;
  linkUrl: string;
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-categories".
 */
export interface MembershipCategory {
  id: number;
  title: string;
  description: string;
  benefits: string;
  annualFee: string;
  feePeriod?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-testimonials".
 */
export interface MemberTestimonial {
  id: number;
  name: string;
  position: string;
  quote: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  slug: string;
  position?: string | null;
  category: 'advisory' | 'board' | 'secretariat' | 'fellow';
  country?: string | null;
  memberCode?: string | null;
  cohortYear?: number | null;
  socialLinks?: {
    instagram?: string | null;
    x?: string | null;
    tiktok?: string | null;
    facebook?: string | null;
    linkedin?: string | null;
  };
  bio?: string | null;
  photo?: (number | null) | Media;
  /**
   * Legacy import URL; used when no Media item is selected.
   */
  imageUrl?: string | null;
  /**
   * Original WordPress publish date (ISO) for fellow ordering
   */
  postDate?: string | null;
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Form submissions from the public website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  formType:
    | 'contact'
    | 'donate'
    | 'volunteer'
    | 'membership'
    | 'service-request'
    | 'newsletter'
    | 'job-application'
    | 'fellowship';
  email?: string | null;
  subject?: string | null;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  jobSlug?: string | null;
  status?: ('new' | 'reviewed' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'hero-feature-cards';
        value: number | HeroFeatureCard;
      } | null)
    | ({
        relationTo: 'membership-categories';
        value: number | MembershipCategory;
      } | null)
    | ({
        relationTo: 'member-testimonials';
        value: number | MemberTestimonial;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  displayName?: T;
  jobTitle?: T;
  phone?: T;
  role?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  heroImage?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  featuredImage?: T;
  imageUrl?: T;
  newsSource?: T;
  newsAuthor?: T;
  newsDate?: T;
  originalUrl?: T;
  featured?: T;
  priority?: T;
  expiryDate?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  author?: T;
  featuredImage?: T;
  imageUrl?: T;
  originalUrl?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  department?: T;
  location?: T;
  jobType?: T;
  summary?: T;
  description?: T;
  requirements?: T;
  status?: T;
  applyUrl?: T;
  jobId?: T;
  category?: T;
  postedAt?: T;
  roleHtml?: T;
  responsibilitiesHtml?: T;
  aboutHtml?: T;
  qualificationsHtml?: T;
  competenciesHtml?: T;
  locationScope?: T;
  appointment?: T;
  requirementsHtml?: T;
  processHtml?: T;
  deadline?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  backgroundImage?: T;
  backgroundImageUrl?: T;
  sideImage?: T;
  sideImageUrl?: T;
  sideVideoUrl?: T;
  showSideImage?: T;
  showApplyOnly?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-feature-cards_select".
 */
export interface HeroFeatureCardsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  linkText?: T;
  linkUrl?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-categories_select".
 */
export interface MembershipCategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  benefits?: T;
  annualFee?: T;
  feePeriod?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-testimonials_select".
 */
export interface MemberTestimonialsSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  quote?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  position?: T;
  category?: T;
  country?: T;
  memberCode?: T;
  cohortYear?: T;
  socialLinks?:
    | T
    | {
        instagram?: T;
        x?: T;
        tiktok?: T;
        facebook?: T;
        linkedin?: T;
      };
  bio?: T;
  photo?: T;
  imageUrl?: T;
  postDate?: T;
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formType?: T;
  email?: T;
  subject?: T;
  payload?: T;
  jobSlug?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  utilityBarLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'linkedin' | 'twitter' | 'youtube' | 'instagram';
        url: string;
        id?: string | null;
      }[]
    | null;
  headerNav?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              flyout?: ('right' | 'left') | null;
              subItems?:
                | {
                    label: string;
                    href: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  address?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  showTranslator?: boolean | null;
  showWhatsappHelp?: boolean | null;
  whatsappHelpLabel?: string | null;
  fellowshipPopupEnabled?: boolean | null;
  fellowshipPopupTitle?: string | null;
  fellowshipPopupBody?: string | null;
  fellowshipPopupDeadline?: string | null;
  fellowshipPopupApplyUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wwd-homepage".
 */
export interface WwdHomepage {
  id: number;
  headerTitle: string;
  headerContent?: string | null;
  intro?: {
    title?: string | null;
    content?: string | null;
    image?: (number | null) | Media;
    /**
     * Legacy import URL; used when no Media item is selected.
     */
    imageUrl?: string | null;
    buttonText?: string | null;
    buttonUrl?: string | null;
  };
  services?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        /**
         * Describe the image for accessibility. Defaults from filename if empty.
         */
        imageAlt?: string | null;
        /**
         * Legacy import URL; used when no Media item is selected.
         */
        imageUrl?: string | null;
        buttonText?: string | null;
        buttonUrl?: string | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-councils-homepage".
 */
export interface IndustryCouncilsHomepage {
  id: number;
  headerTitle: string;
  headerDescription?: string | null;
  headerButtonText?: string | null;
  headerButtonUrl?: string | null;
  intro?: {
    image?: (number | null) | Media;
    /**
     * Legacy import URL; used when no Media item is selected.
     */
    imageUrl?: string | null;
    title?: string | null;
    text?: string | null;
    buttonText?: string | null;
    buttonUrl?: string | null;
  };
  councils?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        /**
         * Describe the image for accessibility. Defaults from filename if empty.
         */
        imageAlt?: string | null;
        /**
         * Legacy import URL; used when no Media item is selected.
         */
        imageUrl?: string | null;
        buttonText?: string | null;
        buttonUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cross-sector-councils-homepage".
 */
export interface CrossSectorCouncilsHomepage {
  id: number;
  intro: {
    title: string;
    description?: string | null;
    image?: (number | null) | Media;
    /**
     * Legacy import URL; used when no Media item is selected.
     */
    imageUrl?: string | null;
    buttonText?: string | null;
    buttonUrl?: string | null;
  };
  councils?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        /**
         * Describe the image for accessibility. Defaults from filename if empty.
         */
        imageAlt?: string | null;
        /**
         * Legacy import URL; used when no Media item is selected.
         */
        imageUrl?: string | null;
        buttonText?: string | null;
        buttonUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-homepage".
 */
export interface MembershipHomepage {
  id: number;
  sectionTitle: string;
  sectionDescription?: string | null;
  sectionCtaText?: string | null;
  sectionCtaUrl?: string | null;
  cards?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        /**
         * Describe the image for accessibility. Defaults from filename if empty.
         */
        imageAlt?: string | null;
        /**
         * Legacy import URL; used when no Media item is selected.
         */
        imageUrl?: string | null;
        buttonText?: string | null;
        buttonUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights-homepage".
 */
export interface InsightsHomepage {
  id: number;
  sectionTitle: string;
  sectionDescription?: string | null;
  sectionCtaText?: string | null;
  sectionCtaUrl?: string | null;
  cards?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        /**
         * Describe the image for accessibility. Defaults from filename if empty.
         */
        imageAlt?: string | null;
        /**
         * Legacy import URL; used when no Media item is selected.
         */
        imageUrl?: string | null;
        buttonText?: string | null;
        buttonUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-homepage".
 */
export interface EventHomepage {
  id: number;
  sectionTitle: string;
  sectionDescription?: string | null;
  sectionCtaText?: string | null;
  sectionCtaUrl?: string | null;
  cards?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        /**
         * Describe the image for accessibility. Defaults from filename if empty.
         */
        imageAlt?: string | null;
        /**
         * Legacy import URL; used when no Media item is selected.
         */
        imageUrl?: string | null;
        buttonText?: string | null;
        buttonUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "get-involved-homepage".
 */
export interface GetInvolvedHomepage {
  id: number;
  sectionTitle: string;
  sectionDescription?: string | null;
  sectionCtaText?: string | null;
  sectionCtaUrl?: string | null;
  cards?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        /**
         * Describe the image for accessibility. Defaults from filename if empty.
         */
        imageAlt?: string | null;
        /**
         * Legacy import URL; used when no Media item is selected.
         */
        imageUrl?: string | null;
        buttonText?: string | null;
        buttonUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-homepage".
 */
export interface NewsHomepage {
  id: number;
  sectionTitle: string;
  sectionDescription?: string | null;
  sectionCtaText?: string | null;
  sectionCtaUrl?: string | null;
  cards?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        /**
         * Describe the image for accessibility. Defaults from filename if empty.
         */
        imageAlt?: string | null;
        /**
         * Legacy import URL; used when no Media item is selected.
         */
        imageUrl?: string | null;
        buttonText?: string | null;
        buttonUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "country-offices-page".
 */
export interface CountryOfficesPage {
  id: number;
  pageTitle: string;
  pageSubtitle: string;
  offices?:
    | {
        /**
         * URL anchor id, e.g. ghana
         */
        slug: string;
        /**
         * Flag emoji
         */
        flag: string;
        countryName: string;
        regionLabel: string;
        headerTheme:
          | 'ghana'
          | 'kenya'
          | 'nigeria'
          | 'south-africa'
          | 'drc'
          | 'liberia'
          | 'sao-tome'
          | 'morocco'
          | 'ethiopia'
          | 'egypt';
        officeStatus: 'headquarters' | 'active' | 'development' | 'planning';
        officeStatusLabel: string;
        contacts?:
          | {
              type: 'location' | 'phone' | 'email' | 'note';
              value: string;
              id?: string | null;
            }[]
          | null;
        events?:
          | {
              title: string;
              status: 'confirmed' | 'planning' | 'development';
              statusLabel: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional — internal path or full URL
         */
        learnMoreUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fellowship-page".
 */
export interface FellowshipPage {
  id: number;
  heroImage?: (number | null) | Media;
  /**
   * Legacy import URL; used when no Media item is selected.
   */
  heroImageUrl?: string | null;
  introText: string;
  cohorts?:
    | {
        yearLabel: string;
        title: string;
        description: string;
        image?: (number | null) | Media;
        /**
         * Describe the image for accessibility. Defaults from filename if empty.
         */
        imageAlt?: string | null;
        /**
         * Legacy import URL; used when no Media item is selected.
         */
        imageUrl?: string | null;
        exploreUrl: string;
        exploreExternal?: boolean | null;
        id?: string | null;
      }[]
    | null;
  cta: {
    eyebrow: string;
    title: string;
    tagline: string;
    sections?:
      | {
          heading: string;
          paragraphs?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          labeledParagraphs?:
            | {
                label: string;
                text: string;
                id?: string | null;
              }[]
            | null;
          listItems?:
            | {
                /**
                 * Simple bullet
                 */
                text?: string | null;
                /**
                 * Bold title (optional)
                 */
                title?: string | null;
                /**
                 * Body after title (optional)
                 */
                body?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    footerParagraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    applyUrl: string;
    contactPhone: string;
    contactEmail: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-page".
 */
export interface MembershipPage {
  id: number;
  headerTitle: string;
  headerSubtitle: string;
  whyJoin: {
    title: string;
    image?: (number | null) | Media;
    /**
     * Describe the image for accessibility. Defaults from filename if empty.
     */
    imageAlt?: string | null;
    /**
     * Legacy import URL; used when no Media item is selected.
     */
    imageUrl?: string | null;
    body: string;
    ctaLabel: string;
    ctaHref: string;
  };
  benefits: {
    title: string;
    intro: string;
    image?: (number | null) | Media;
    /**
     * Describe the image for accessibility. Defaults from filename if empty.
     */
    imageAlt?: string | null;
    /**
     * Legacy import URL; used when no Media item is selected.
     */
    imageUrl?: string | null;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  categoriesIntro: {
    title: string;
    subtitle: string;
  };
  footerCtas: {
    applyLabel: string;
    applyHref: string;
    guideLabel: string;
    guideHref: string;
  };
  testimonialsHeaderTitle: string;
  testimonialsHeaderSubtitle: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "get-involved-page".
 */
export interface GetInvolvedPage {
  id: number;
  intro: {
    title: string;
    body: string;
    image?: (number | null) | Media;
    /**
     * Describe the image for accessibility. Defaults from filename if empty.
     */
    imageAlt?: string | null;
    /**
     * Legacy import URL; used when no Media item is selected.
     */
    imageUrl?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    id?: string | null;
  };
  cards?:
    | {
        title: string;
        body: string;
        image?: (number | null) | Media;
        /**
         * Describe the image for accessibility. Defaults from filename if empty.
         */
        imageAlt?: string | null;
        /**
         * Legacy import URL; used when no Media item is selected.
         */
        imageUrl?: string | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerships-page".
 */
export interface PartnershipsPage {
  id: number;
  headerTitle: string;
  introText: string;
  listCards?:
    | {
        id: string;
        title: string;
        image?: (number | null) | Media;
        /**
         * Describe the image for accessibility. Defaults from filename if empty.
         */
        imageAlt?: string | null;
        /**
         * Legacy import URL; used when no Media item is selected.
         */
        imageUrl?: string | null;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  getStarted: {
    title: string;
    body: string;
    image?: (number | null) | Media;
    /**
     * Describe the image for accessibility. Defaults from filename if empty.
     */
    imageAlt?: string | null;
    /**
     * Legacy import URL; used when no Media item is selected.
     */
    imageUrl?: string | null;
    requestLabel: string;
    requestEmail: string;
    guideLabel: string;
    guideHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donate-page".
 */
export interface DonatePage {
  id: number;
  headerTitle: string;
  headerTagline: string;
  heroTitle: string;
  heroParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  whyTitle: string;
  whyIntro: string;
  whyBenefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  whoTitle: string;
  whoIntro: string;
  donorCategories?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  transparencyTitle: string;
  transparencyText: string;
  ctaTitle: string;
  ctaText: string;
  financeEmail: string;
  financePhone: string;
  thankYouTitle: string;
  thankYouText: string;
  formTitle: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-page".
 */
export interface VolunteerPage {
  id: number;
  headerTitle: string;
  headerTagline: string;
  heroTitle: string;
  heroText: string;
  heroText2: string;
  whyTitle: string;
  whyIntro: string;
  whyBenefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  rolesTitle: string;
  roles?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  whoTitle: string;
  whoIntro: string;
  whoCanApply?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  commitmentTitle: string;
  commitmentText: string;
  formTitle: string;
  formSubtitle: string;
  formEmail: string;
  submitButtonText: string;
  thankYouTitle: string;
  thankYouText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-listing-page".
 */
export interface NewsListingPage {
  id: number;
  introTitle: string;
  introBody: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  introTitle: string;
  introBody: string;
  introImage?: (number | null) | Media;
  /**
   * Describe the image for accessibility. Defaults from filename if empty.
   */
  introImageAlt?: string | null;
  /**
   * Legacy import URL; used when no Media item is selected.
   */
  introImageUrl?: string | null;
  email: string;
  phone: string;
  address: string;
  officeHours: string;
  formBlurbTitle: string;
  formBlurbText: string;
  formTitle: string;
  formSubtitle: string;
  formEmail: string;
  submitButtonText: string;
  subjectOptions?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  locationTitle: string;
  locationIntro: string;
  mapEmbedUrl: string;
  socialTitle: string;
  socialIntro: string;
  socialLinks?:
    | {
        platform: string;
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  newsletterTitle: string;
  newsletterBody: string;
  newsletterSubmitLabel: string;
  newsletterSuccessMessage: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  sectionTitle: string;
  mainContent: string;
  visionContent: string;
  missionContent: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  utilityBarLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  headerNav?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              flyout?: T;
              subItems?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  address?: T;
  contactEmail?: T;
  contactPhone?: T;
  showTranslator?: T;
  showWhatsappHelp?: T;
  whatsappHelpLabel?: T;
  fellowshipPopupEnabled?: T;
  fellowshipPopupTitle?: T;
  fellowshipPopupBody?: T;
  fellowshipPopupDeadline?: T;
  fellowshipPopupApplyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wwd-homepage_select".
 */
export interface WwdHomepageSelect<T extends boolean = true> {
  headerTitle?: T;
  headerContent?: T;
  intro?:
    | T
    | {
        title?: T;
        content?: T;
        image?: T;
        imageUrl?: T;
        buttonText?: T;
        buttonUrl?: T;
      };
  services?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        buttonText?: T;
        buttonUrl?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-councils-homepage_select".
 */
export interface IndustryCouncilsHomepageSelect<T extends boolean = true> {
  headerTitle?: T;
  headerDescription?: T;
  headerButtonText?: T;
  headerButtonUrl?: T;
  intro?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        title?: T;
        text?: T;
        buttonText?: T;
        buttonUrl?: T;
      };
  councils?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        buttonText?: T;
        buttonUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cross-sector-councils-homepage_select".
 */
export interface CrossSectorCouncilsHomepageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        imageUrl?: T;
        buttonText?: T;
        buttonUrl?: T;
      };
  councils?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        buttonText?: T;
        buttonUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-homepage_select".
 */
export interface MembershipHomepageSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionDescription?: T;
  sectionCtaText?: T;
  sectionCtaUrl?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        buttonText?: T;
        buttonUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights-homepage_select".
 */
export interface InsightsHomepageSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionDescription?: T;
  sectionCtaText?: T;
  sectionCtaUrl?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        buttonText?: T;
        buttonUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-homepage_select".
 */
export interface EventHomepageSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionDescription?: T;
  sectionCtaText?: T;
  sectionCtaUrl?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        buttonText?: T;
        buttonUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "get-involved-homepage_select".
 */
export interface GetInvolvedHomepageSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionDescription?: T;
  sectionCtaText?: T;
  sectionCtaUrl?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        buttonText?: T;
        buttonUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-homepage_select".
 */
export interface NewsHomepageSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionDescription?: T;
  sectionCtaText?: T;
  sectionCtaUrl?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        buttonText?: T;
        buttonUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "country-offices-page_select".
 */
export interface CountryOfficesPageSelect<T extends boolean = true> {
  pageTitle?: T;
  pageSubtitle?: T;
  offices?:
    | T
    | {
        slug?: T;
        flag?: T;
        countryName?: T;
        regionLabel?: T;
        headerTheme?: T;
        officeStatus?: T;
        officeStatusLabel?: T;
        contacts?:
          | T
          | {
              type?: T;
              value?: T;
              id?: T;
            };
        events?:
          | T
          | {
              title?: T;
              status?: T;
              statusLabel?: T;
              id?: T;
            };
        learnMoreUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fellowship-page_select".
 */
export interface FellowshipPageSelect<T extends boolean = true> {
  heroImage?: T;
  heroImageUrl?: T;
  introText?: T;
  cohorts?:
    | T
    | {
        yearLabel?: T;
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        exploreUrl?: T;
        exploreExternal?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        tagline?: T;
        sections?:
          | T
          | {
              heading?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              labeledParagraphs?:
                | T
                | {
                    label?: T;
                    text?: T;
                    id?: T;
                  };
              listItems?:
                | T
                | {
                    text?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
            };
        footerParagraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        applyUrl?: T;
        contactPhone?: T;
        contactEmail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-page_select".
 */
export interface MembershipPageSelect<T extends boolean = true> {
  headerTitle?: T;
  headerSubtitle?: T;
  whyJoin?:
    | T
    | {
        title?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        body?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        intro?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  categoriesIntro?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  footerCtas?:
    | T
    | {
        applyLabel?: T;
        applyHref?: T;
        guideLabel?: T;
        guideHref?: T;
      };
  testimonialsHeaderTitle?: T;
  testimonialsHeaderSubtitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "get-involved-page_select".
 */
export interface GetInvolvedPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  cards?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerships-page_select".
 */
export interface PartnershipsPageSelect<T extends boolean = true> {
  headerTitle?: T;
  introText?: T;
  listCards?:
    | T
    | {
        id?: T;
        title?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  getStarted?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        imageAlt?: T;
        imageUrl?: T;
        requestLabel?: T;
        requestEmail?: T;
        guideLabel?: T;
        guideHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donate-page_select".
 */
export interface DonatePageSelect<T extends boolean = true> {
  headerTitle?: T;
  headerTagline?: T;
  heroTitle?: T;
  heroParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  whyTitle?: T;
  whyIntro?: T;
  whyBenefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  whoTitle?: T;
  whoIntro?: T;
  donorCategories?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  transparencyTitle?: T;
  transparencyText?: T;
  ctaTitle?: T;
  ctaText?: T;
  financeEmail?: T;
  financePhone?: T;
  thankYouTitle?: T;
  thankYouText?: T;
  formTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-page_select".
 */
export interface VolunteerPageSelect<T extends boolean = true> {
  headerTitle?: T;
  headerTagline?: T;
  heroTitle?: T;
  heroText?: T;
  heroText2?: T;
  whyTitle?: T;
  whyIntro?: T;
  whyBenefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  rolesTitle?: T;
  roles?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  whoTitle?: T;
  whoIntro?: T;
  whoCanApply?:
    | T
    | {
        text?: T;
        id?: T;
      };
  commitmentTitle?: T;
  commitmentText?: T;
  formTitle?: T;
  formSubtitle?: T;
  formEmail?: T;
  submitButtonText?: T;
  thankYouTitle?: T;
  thankYouText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-listing-page_select".
 */
export interface NewsListingPageSelect<T extends boolean = true> {
  introTitle?: T;
  introBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  introTitle?: T;
  introBody?: T;
  introImage?: T;
  introImageAlt?: T;
  introImageUrl?: T;
  email?: T;
  phone?: T;
  address?: T;
  officeHours?: T;
  formBlurbTitle?: T;
  formBlurbText?: T;
  formTitle?: T;
  formSubtitle?: T;
  formEmail?: T;
  submitButtonText?: T;
  subjectOptions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  locationTitle?: T;
  locationIntro?: T;
  mapEmbedUrl?: T;
  socialTitle?: T;
  socialIntro?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  newsletterTitle?: T;
  newsletterBody?: T;
  newsletterSubmitLabel?: T;
  newsletterSuccessMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  sectionTitle?: T;
  mainContent?: T;
  visionContent?: T;
  missionContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}